// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Video struct {
	ID           uint64         `json:"id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	PublishedAt  time.Time      `json:"published_at"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	VideoUrl     string         `json:"video_url"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
