version: '3.8'

services:
  app:
    build: .
    container_name: go-youtube-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: yourdbname
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdbname
    volumes:
      - mysql_data:/var/lib/mysql
